#ifndef HEADER_VTT_INTERPROCESS_DETAILS_MAIN
#define HEADER_VTT_INTERPROCESS_DETAILS_MAIN

#pragma once

#define VTT_INTERPROCESS_DLL_EXPORTS

#define VTT_SZ_INTERPROCESS_NAMED_OBJECTS_PREFIX "vtt interprocess "

//#define _DEBUG_LOGGING

#ifndef _DEBUG
#undef _DEBUG_LOGGING
#endif

#endif